### ISSUE TITLE
Disease risk model - disinfect vs. disinfest

### ISSUE THREAD

**Issue by jenniferparke** [skp703/CW3#8]
I haven't had a chance to go through all 44 questions yet, but all occasions where "disinfect" is applied to water, pots, bench surfaces should be changed to "disinfest". Water, pots, bench surfaces can be **infested** with pathogens, but they can't be **infected** with pathogens because they are not  living things. So, by the same reasoning they can be disinfested but not disinfected.

**Comment by skp703** [comment]
Ahh makes sense.  Fixed!
